name: Test
on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Inputs: None'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Version'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          version: '0.33.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: File Paths'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          file_paths: 'app/views/**/*.html.haml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Fail Level'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          fail_level: 'warning'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Additional Gems'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          additional_gems: 'rubocop-rails rubocop-performance'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Additional Gems with Versions'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          additional_gems: "'rubocop-rails:2.3.2' 'rubocop-performance:~>1.5'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Exclude Paths'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          exclude_paths: 'app/views/devise/confirmations/*.html.haml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Inputs: Config Path'
        uses: andrewmcodes/haml-lint-action@212ea237b5ef6d9906fa67a1fb0e047c463d9dcd
        with:
          config_path: 'config/.haml-lint.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
